version: "3.9"

services:
  grpc-server:
    container_name: grpc-server
    build: .
    command: "grpc-server"
    environment:
      APP_ADDRESS: "0.0.0.0:4000"
    ports:
      - "4000:4000"
    networks:
      - app_network
    restart: unless-stopped

  grpc-client:
    container_name: grpc-client
    build: .
    command: "grpc-client"
    environment:
      SERVER_ADDRESS: "grpc-server:4000"
    networks:
      - app_network
    depends_on:
      - grpc-server
    links:
      - grpc-server

networks:
  app_network:
    driver: bridge