version: "3.9"

services:
  grpc-server:
    container_name: "grpc-server"
    build: .
    command: "grpc-server"
    env_file:
      - server.env
    ports:
      - "4000:4000"
    networks:
      - app_network
    restart: unless-stopped
    depends_on:
      - postgres

  grpc-client:
    container_name: "grpc-client"
    build: .
    command: "grpc-client"
    environment:
      SERVER_ADDRESS: "grpc-server:4000"
    networks:
      - app_network
    depends_on:
      - grpc-server

  postgres:
    container_name: "postgres-db"
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/data/postgres"
    volumes:
      - ./postgres:/data/postgres/
    ports:
      - "5432:5432"
    networks:
      - app_network
    restart: unless-stopped

  postgres-test:
    container_name: "postgres-test"
    build: .
#    command: "postgres-test"
    environment:
      POSTGRES_ADDRESS: "postgres-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_TABLE: "grpc_messages"
    networks:
      - app_network
    depends_on:
      - postgres


networks:
  app_network:
    driver: bridge