version: "3.9"

services:
  grpc-server:
    container_name: grpc-server
    build: .
    environment:
      APP_ADDRESS: 0.0.0.0:4000
    command: "grpc-server"
    ports:
      - "4000:4000"
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge